Run tests as part of CI job
kubeshop/monokle-core pull request #477
Opened 2023-08-10 11:39 UTC by f1ames

This PR add test run on CI.

Looks like some tests in `validation` package are failing, this needs to be checked before we merge this PR.

## Changes

- Added test job to CI workflow.

## Fixes

- Test snapshot in `validation` package.

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2023-08-10 11:51 UTC, f1ames commented
> Looks like some tests in `validation` package are failing, this needs to be checked before we merge this PR.

It seems it was caused by some work done with suppression 🤔 It works on d35bf2338d91e7a16f95cd0a34f9b1aa43df333d but it's already broken on 62760687585a89a8f3f770b30a409d80ec58825d, which means it was broken somewhere here:

![image](https://github.com/kubeshop/monokle-core/assets/1061942/a9abcf51-61da-4fff-9bbe-c126822da87d)

I'll take a look after I'm done with #476.

2023-08-25 11:48 UTC, murarustefaan requested changes

2023-08-25 11:48 UTC, murarustefaan commented on .github/workflows/test-build.yml
> +        run: npm install
run `npm ci` rather than install

2023-08-25 12:34 UTC, murarustefaan approved these changes
lgtm

2023-08-25 12:36 UTC, merged